name: Action para desplegar aplicaciones Java Spring Boot 2.5.12
description: 'Esta acción despliega aplicaciones Java Spring Boot 2.5.12'
inputs:
  ########################################################################
  # Conexión al servidor
  ########################################################################
  server_ip:
    description: 'Dirección IP del servidor donde se desplegará la aplicación'
    required: true
  remote_user:
    description: 'Usuario para conectarse al servidor remoto'
    required: true
  ########################################################################
  # Configuración del sitio/webapp en IIS
  ########################################################################
  artifact_file_name:
    description: 'Nombre del archivo artefacto a desplegar (sin extensión)'
    required: true
  project_path:
    description: 'Ruta del proyecto en el servidor remoto'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Descargar artefacto
      uses: actions/download-artifact@v4
      with:
        name: '${{ inputs.artifact_file_name }}'
        path: 'C:\artifacts\net-framework'
      
    - name: Desplegar en aplicación .NET Framework
      run: |
        echo "Crear directorio para la aplicación en el servidor remoto"
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} mkdir \"${{ inputs.project_path }}\${{ inputs.artifact_file_name }}\"

        echo "Desplegando aplicación .NET Framework en el servidor remoto"
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} move \"C:\artifacts\net-framework\${{ inputs.artifact_file_name }}.zip\" \"${{ inputs.project_path }}\${{ inputs.artifact_file_name }}\"

        echo "Descompresion de artefacto en el servidor remoto"
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} powershell -Command "Expand-Archive -Path \"${{ inputs.project_path }}\${{ inputs.artifact_file_name }}\${{ inputs.artifact_file_name }}.zip\" -DestinationPath \"${{ inputs.project_path }}\${{ inputs.artifact_file_name }}\" -Force"

        echo "Eliminar archivo ZIP del servidor remoto"
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} del \"${{ inputs.project_path }}\${{ inputs.artifact_file_name }}\${{ inputs.artifact_file_name }}.zip\"
      shell: cmd