name: Action para desplegar aplicaciones Java Spring Boot 2.5.12
description: 'Esta acción despliega aplicaciones Java Spring Boot 2.5.12'
inputs:
  ########################################################################
  # Conexión al servidor
  ########################################################################
  server_ip:
    description: 'Dirección IP del servidor donde se desplegará la aplicación'
    required: true
  remote_user:
    description: 'Usuario para conectarse al servidor remoto'
    required: true
  ########################################################################
  # Configuración de la aplicación
  ########################################################################
  artifact_file_name:
    description: 'Nombre del archivo del artefacto a desplegar (incluyendo extensión)'
    required: true
  tomcat_path:
    description: 'Ruta del directorio webapps de Tomcat en el servidor remoto'
    required: true
    default: 'C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps'
  tomcat_port:
    description: 'Puerto en el que Tomcat servirá la aplicación'
    required: false
    default: '8080'
runs:
  using: 'composite'
  steps:

    - name: Descargar artefacto desde GitHub Packages
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.artifact_file_name }}
        path: C:\artifacts\java-springboot-2.5.12

    - name: Desplegar en Tomcat
      shell: cmd
      run: |
        echo "Desplegando aplicación Java Spring Boot 2.5.12 en Tomcat..."
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} move \"C:\artifacts\java-springboot-2.5.12\${{ inputs.artifact_file_name }}\" \"${{ inputs.tomcat_path }}\"
        echo "Despliegue en Tomcat completado..."