name: Node.js Workflow
on:
  workflow_call:

jobs:
  
  build_test:
    runs-on: self-hosted
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: jgallardo-clever/test-pipelines-fge
          path: workflow-repository

      - name: Build app
        uses: ./workflow-repository/.github/actions/nodejs/build

      - name: Test app
        uses: ./workflow-repository/.github/actions/nodejs/test

      - name: Code analysis
        run: echo "Code analysis"

      - name: Upload artifact
        run: echo "Upload artifact"   

  deploy:
    runs-on: self-hosted
    needs: build_test
    steps:
      - name: Download artifact
        run: echo "Download artifact"

      - name: Deploy to server
        run: echo "Deploy to server"
