name: .NET Framework Workflow
on:
  workflow_call:

jobs:
  
  build_test:
    runs-on: self-hosted
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: jgallardo-clever/test-pipelines-fge
          path: workflow-repository

      - name: Build app
        uses: ./workflow-repository/.github/actions/netframework/build

      - name: Test app
        uses: ./workflow-repository/.github/actions/netframework/test

      - name: Code analysis
        uses: ./workflow-repository/.github/actions/netframework/code-analysis
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload artifact
        uses: ./workflow-repository/.github/actions/netframework/upload-artifact

  deploy:
    runs-on: self-hosted
    needs: build_test
    steps:
      - name: Deploy to server
        run: echo "Deploy to server"