name: Node.js Workflow
on:
  workflow_call:

jobs:
  
  build_test:
    outputs:
      artifact_name: ${{ steps.upload_artifact.outputs.artifact_file_name }}
    runs-on: self-hosted
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: jgallardo-clever/test-pipelines-fge
          path: workflow-repository

      - name: Build app
        uses: ./workflow-repository/.github/actions/nodejs/build

      - name: Test app
        uses: ./workflow-repository/.github/actions/nodejs/test

      - name: Code analysis
        uses: ./workflow-repository/.github/actions/nodejs/code-analysis
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload artifact
        id: upload_artifact
        uses: ./workflow-repository/.github/actions/nodejs/upload-artifact

  deploy:
    runs-on: self-hosted
    needs: build_test
    steps:
      - name: Deploy to server
        uses: ./workflow-repository/.github/actions/nodejs/deploy
        with:
          server_ip: ${{ secrets.server_ip }}
          remote_user: ${{ secrets.remote_user }}
          artifact_file_name: ${{ needs.build_test.outputs.artifact_name }}
          project_path: ${{ secrets.project_path }}
